export const ROLE_COLORS = {
  Por: { bg: "#f59e0b22", text: "#f59e0b", border: "#f59e0b44" },
  // Difensori → verde (primo ruolo Dc/Dd/Ds/B)
  Dc:  { bg: "#10b98122", text: "#34d399", border: "#10b98144" },
  Dd:  { bg: "#10b98122", text: "#34d399", border: "#10b98144" },
  Ds:  { bg: "#10b98122", text: "#34d399", border: "#10b98144" },
  B:   { bg: "#10b98122", text: "#34d399", border: "#10b98144" },
  // Centrocampisti → blu (primo ruolo E/M/C)
  E:   { bg: "#3b82f622", text: "#60a5fa", border: "#3b82f644" },
  M:   { bg: "#3b82f622", text: "#60a5fa", border: "#3b82f644" },
  C:   { bg: "#3b82f622", text: "#60a5fa", border: "#3b82f644" },
  // Trequartisti → viola (primo ruolo W/T)
  T:   { bg: "#8b5cf622", text: "#a78bfa", border: "#8b5cf644" },
  W:   { bg: "#8b5cf622", text: "#a78bfa", border: "#8b5cf644" },
  // Attaccanti → rosso (primo ruolo A/Pc)
  A:   { bg: "#ef444422", text: "#f87171", border: "#ef444444" },
  Pc:  { bg: "#ef444422", text: "#f87171", border: "#ef444444" },
};

export function getRoleColor(ruolo) {
  const primary = ruolo.split(";")[0].trim();
  return ROLE_COLORS[primary] || { bg: "#ffffff11", text: "#aaa", border: "#ffffff22" };
}

export const FP_THRESHOLDS = [
  { max: 40,       label: "Sicuro",                     color: "#10b981" },
  { max: 45,       label: "Multa 5M",                   color: "#f59e0b" },
  { max: 50,       label: "Multa 10M + blocco 1 sett.", color: "#f97316" },
  { max: 55,       label: "Multa 15M + blocco 2 sett.", color: "#ef4444" },
  { max: Infinity, label: "CRITICO",                    color: "#991b1b" },
];

export function getFPStatus(fp) {
  for (const t of FP_THRESHOLDS) if (fp <= t.max) return t;
  return FP_THRESHOLDS[FP_THRESHOLDS.length - 1];
}

export function getSCColor(used, cap = 75) {
  const p = used / cap;
  if (p > 1)    return "#ef4444";
  if (p > 0.97) return "#f97316";
  if (p > 0.92) return "#f59e0b";
  return "#10b981";
}

export const TEAMS = [
  { id:1, name:"Alcool Campi",   tag:"ALC", color:"#e8c84a", allenatore:"Palladino",          bilancio:24.65, salaryUsed:70.8, giocatori:27, u21:1, fairPlay1:50.65, fairPlay2:-9.5,  penalita:0, guadGiornate:66.2,  guadObiettivi:-2,  guadInv:-19.8, clausoleIn:14.75, clausoleOut:35.1,  svincoliOrdinari:4 },
  { id:2, name:"Borjcellona",    tag:"BOR", color:"#a855f7", allenatore:"Spalletti",           bilancio:24.15, salaryUsed:75.0, giocatori:27, u21:3, fairPlay1:40.65, fairPlay2:1.8,   penalita:0, guadGiornate:107.0, guadObiettivi:10,  guadInv:-16.1, clausoleIn:7.5,   clausoleOut:10.0,  svincoliOrdinari:3 },
  { id:3, name:"Balillareal",    tag:"BAL", color:"#3b82f6", allenatore:"Italiano & Fabregas", bilancio:5.8,   salaryUsed:72.1, giocatori:25, u21:5, fairPlay1:54.55, fairPlay2:15.5,  penalita:1, guadGiornate:80.8,  guadObiettivi:0,   guadInv:-13.0, clausoleIn:14.0,  clausoleOut:9.0,   svincoliOrdinari:0 },
  { id:4, name:"AK Toio",        tag:"AKT", color:"#10b981", allenatore:"Allegri",             bilancio:23.54, salaryUsed:72.2, giocatori:28, u21:2, fairPlay1:26.21, fairPlay2:9.75,  penalita:0, guadGiornate:72.8,  guadObiettivi:20,  guadInv:-10.0, clausoleIn:10.0,  clausoleOut:14.25, svincoliOrdinari:1 },
  { id:5, name:"Shalpe 104",     tag:"SHA", color:"#f97316", allenatore:"Chivu",               bilancio:24.5,  salaryUsed:74.5, giocatori:28, u21:1, fairPlay1:12.55, fairPlay2:15.6,  penalita:1, guadGiornate:79.5,  guadObiettivi:3,   guadInv:0.0,   clausoleIn:6.0,   clausoleOut:8.5,   svincoliOrdinari:1 },
  { id:6, name:"Finocchiona AC", tag:"FIN", color:"#ef4444", allenatore:"Conte",               bilancio:8.15,  salaryUsed:74.8, giocatori:25, u21:4, fairPlay1:60.65, fairPlay2:6.0,   penalita:2, guadGiornate:92.3,  guadObiettivi:0,   guadInv:-16.0, clausoleIn:36.5,  clausoleOut:9.0,   svincoliOrdinari:2 },
  { id:7, name:"Agnus Dei FC",   tag:"AGD", color:"#06b6d4", allenatore:"Sarri & Vanoli",      bilancio:31.1,  salaryUsed:66.0, giocatori:24, u21:1, fairPlay1:20.4,  fairPlay2:5.0,   penalita:3, guadGiornate:56.0,  guadObiettivi:0,   guadInv:-8.0,  clausoleIn:15.1,  clausoleOut:15.5,  svincoliOrdinari:0 },
  { id:8, name:"Wehrmacht FC",    tag:"CON", color:"#ec4899", allenatore:"Gasperini",           bilancio:5.4,   salaryUsed:70.1, giocatori:28, u21:2, fairPlay1:28.65, fairPlay2:17.0,  penalita:9, guadGiornate:43.9,  guadObiettivi:5,   guadInv:0.0,   clausoleIn:16.0,  clausoleOut:15.0,  svincoliOrdinari:1 },
];

export const ROSTERS = {
  "Alcool Campi": [
    { ruolo:"Por", anni:25, nome:"Carnesecchi", quot:15, stip:3.0, clausola:30 },
    { ruolo:"Por", anni:33, nome:"Sportiello", quot:1, stip:0.2, clausola:2 },
    { ruolo:"Dc", anni:31, nome:"Maripan", quot:11, stip:2.2, clausola:22 },
    { ruolo:"Dc", anni:27, nome:"Beukema", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Dc", anni:22, nome:"Scalvini", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:32, nome:"Djimsiti", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:31, nome:"Rrahmani", quot:11, stip:2.2, clausola:22 },
    { ruolo:"Dc", anni:26, nome:"N'Dicka", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Dd;Dc", anni:23, nome:"Kristensen T.", quot:7, stip:1.4, clausola:14 },
    { ruolo:"B;Ds;E", anni:17, nome:"Ahanor", quot:7, stip:1.4, clausola:14 },
    { ruolo:"E", anni:25, nome:"Bellanova", quot:12, stip:2.4, clausola:24 },
    { ruolo:"E", anni:29, nome:"Dumfries", quot:11, stip:2.2, clausola:22 },
    { ruolo:"E", anni:33, nome:"Zappacosta", quot:8, stip:1.6, clausola:16 },
    { ruolo:"M;C", anni:24, nome:"Frendrup", quot:10, stip:2.0, clausola:20 },
    { ruolo:"M;C", anni:22, nome:"Perrone", quot:16, stip:3.2, clausola:32 },
    { ruolo:"C", anni:28, nome:"Barella", quot:19, stip:3.8, clausola:38 },
    { ruolo:"E;W", anni:26, nome:"Zerbin", quot:6, stip:1.2, clausola:12 },
    { ruolo:"E;W", anni:24, nome:"Luis Henrique", quot:6, stip:1.2, clausola:12 },
    { ruolo:"C;T", anni:32, nome:"Malinovskyi", quot:15, stip:3.0, clausola:30 },
    { ruolo:"W;T", anni:25, nome:"Tramoni M.", quot:12, stip:2.4, clausola:24 },
    { ruolo:"A", anni:24, nome:"De Ketelaere", quot:16, stip:3.2, clausola:32 },
    { ruolo:"A", anni:25, nome:"Cambiaghi", quot:17, stip:3.4, clausola:34 },
    { ruolo:"A", anni:32, nome:"Dybala", quot:13, stip:2.6, clausola:26 },
    { ruolo:"A", anni:29, nome:"Adams C.", quot:17, stip:3.4, clausola:34 },
    { ruolo:"Pc", anni:24, nome:"Stulic", quot:13, stip:2.6, clausola:26 },
    { ruolo:"Pc", anni:25, nome:"Vlahovic", quot:24, stip:4.8, clausola:48 },
    { ruolo:"Pc", anni:25, nome:"David", quot:13, stip:2.6, clausola:26 },
  ],
  "Borjcellona": [
    { ruolo:"Por", anni:33, nome:"Perin", quot:1, stip:0.2, clausola:2 },
    { ruolo:"Por", anni:28, nome:"Di Gregorio", quot:16, stip:3.2, clausola:32 },
    { ruolo:"Dc", anni:24, nome:"Pavlovic", quot:17, stip:3.4, clausola:34 },
    { ruolo:"Dc", anni:26, nome:"Gabbia", quot:6, stip:1.2, clausola:12 },
    { ruolo:"Dc", anni:31, nome:"Rugani", quot:2, stip:0.4, clausola:4 },
    { ruolo:"Dc", anni:25, nome:"Bisseck", quot:9, stip:1.8, clausola:18 },
    { ruolo:"Dc", anni:28, nome:"Bremer", quot:13, stip:2.6, clausola:26 },
    { ruolo:"Ds;Dc", anni:26, nome:"Heggem", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Ds;E", anni:22, nome:"Angori", quot:5, stip:1.0, clausola:10 },
    { ruolo:"B;Ds;E", anni:26, nome:"Carlos Augusto", quot:11, stip:2.2, clausola:22 },
    { ruolo:"E", anni:28, nome:"Dimarco", quot:26, stip:5.2, clausola:52 },
    { ruolo:"E", anni:22, nome:"Bernasconi", quot:7, stip:1.4, clausola:14 },
    { ruolo:"M;C", anni:23, nome:"Konè I.", quot:17, stip:3.4, clausola:34 },
    { ruolo:"M;C", anni:27, nome:"McKennie", quot:11, stip:2.2, clausola:22 },
    { ruolo:"M;C", anni:24, nome:"Thuram K.", quot:17, stip:3.4, clausola:34 },
    { ruolo:"C", anni:22, nome:"Atta", quot:16, stip:3.2, clausola:32 },
    { ruolo:"C;T", anni:22, nome:"Casadei", quot:12, stip:2.4, clausola:24 },
    { ruolo:"W;A", anni:31, nome:"Bernardeschi", quot:8, stip:1.6, clausola:16 },
    { ruolo:"W;A", anni:28, nome:"Orsolini", quot:29, stip:5.8, clausola:58 },
    { ruolo:"W;A", anni:23, nome:"Ondrejka", quot:6, stip:1.2, clausola:12 },
    { ruolo:"W;A", anni:24, nome:"Zaragoza", quot:6, stip:1.2, clausola:12 },
    { ruolo:"A", anni:23, nome:"Esposito Se.", quot:17, stip:3.4, clausola:34 },
    { ruolo:"A", anni:20, nome:"Yildiz", quot:25, stip:5.0, clausola:50 },
    { ruolo:"Pc", anni:27, nome:"Davis K.", quot:14, stip:2.8, clausola:28 },
    { ruolo:"Pc", anni:32, nome:"Lukaku", quot:15, stip:3.0, clausola:30 },
    { ruolo:"Pc", anni:20, nome:"Esposito F.P.", quot:20, stip:4.0, clausola:40 },
    { ruolo:"Pc", anni:16, nome:"Arena A.", quot:1, stip:0.2, clausola:2 },
  ],
  "Balillareal": [
    { ruolo:"Por", anni:26, nome:"Ravaglia F.", quot:9, stip:1.8, clausola:18 },
    { ruolo:"Por", anni:30, nome:"Butez", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Por", anni:34, nome:"Skorupski", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Dc", anni:29, nome:"Baschirotto", quot:14, stip:2.8, clausola:28 },
    { ruolo:"Dc", anni:20, nome:"Ramon", quot:11, stip:2.2, clausola:22 },
    { ruolo:"Dc", anni:30, nome:"Akanji", quot:9, stip:1.8, clausola:18 },
    { ruolo:"Dc", anni:22, nome:"Ghilardi", quot:4, stip:0.8, clausola:8 },
    { ruolo:"Ds;E", anni:25, nome:"Miranda J.", quot:9, stip:1.8, clausola:18 },
    { ruolo:"Ds;E", anni:23, nome:"Doig", quot:6, stip:1.2, clausola:12 },
    { ruolo:"Ds;E", anni:24, nome:"Gutierrez", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dd;E", anni:30, nome:"Vojvoda", quot:7, stip:1.4, clausola:14 },
    { ruolo:"Dd;E", anni:21, nome:"Norton-Cuffy", quot:4, stip:0.8, clausola:8 },
    { ruolo:"E;M", anni:27, nome:"Tourè I.", quot:8, stip:1.6, clausola:16 },
    { ruolo:"M;C", anni:30, nome:"Zambo Anguissa", quot:22, stip:4.4, clausola:44 },
    { ruolo:"M;C", anni:26, nome:"Ederson D.S.", quot:12, stip:2.4, clausola:24 },
    { ruolo:"M;C", anni:23, nome:"Keita M.", quot:9, stip:1.8, clausola:18 },
    { ruolo:"C;T", anni:29, nome:"McTominay", quot:26, stip:5.2, clausola:52 },
    { ruolo:"C;W;T", anni:24, nome:"Da Cunha", quot:13, stip:2.6, clausola:26 },
    { ruolo:"T;A", anni:21, nome:"Paz N.", quot:31, stip:6.2, clausola:62 },
    { ruolo:"W;A", anni:20, nome:"Diao", quot:18, stip:3.6, clausola:36 },
    { ruolo:"W;A", anni:26, nome:"Solomon", quot:10, stip:2.0, clausola:20 },
    { ruolo:"A", anni:26, nome:"Malen", quot:15, stip:3.0, clausola:30 },
    { ruolo:"Pc", anni:21, nome:"Castro S.", quot:19, stip:3.8, clausola:38 },
    { ruolo:"Pc", anni:23, nome:"Orban G.", quot:15, stip:3.0, clausola:30 },
    { ruolo:"Pc", anni:26, nome:"Douvikas", quot:24, stip:4.8, clausola:48 },
  ],
  "AK Toio": [
    { ruolo:"Por", anni:35, nome:"Terracciano", quot:1, stip:0.2, clausola:2 },
    { ruolo:"Por", anni:30, nome:"Maignan", quot:16, stip:3.2, clausola:32 },
    { ruolo:"Dc", anni:30, nome:"Hermoso", quot:12, stip:2.4, clausola:24 },
    { ruolo:"Dc", anni:32, nome:"Diego Carlos", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Dc", anni:27, nome:"Gatti", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:20, nome:"Comuzzo", quot:7, stip:1.4, clausola:14 },
    { ruolo:"Dc", anni:28, nome:"Gaspar K.", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:26, nome:"Bastoni", quot:16, stip:3.2, clausola:32 },
    { ruolo:"Dc", anni:22, nome:"Provstgaard", quot:5, stip:1.0, clausola:10 },
    { ruolo:"Ds;E", anni:20, nome:"Bartesaghi", quot:12, stip:2.4, clausola:24 },
    { ruolo:"Ds;E", anni:27, nome:"Estupinan", quot:3, stip:0.6, clausola:6 },
    { ruolo:"Dd;E", anni:25, nome:"Holm", quot:14, stip:2.8, clausola:28 },
    { ruolo:"Dd;E", anni:30, nome:"Ehizibue", quot:5, stip:1.0, clausola:10 },
    { ruolo:"B;Dd;E", anni:26, nome:"Delprato", quot:8, stip:1.6, clausola:16 },
    { ruolo:"M;C", anni:30, nome:"Cristante", quot:9, stip:1.8, clausola:18 },
    { ruolo:"M;C", anni:24, nome:"Konè M.", quot:15, stip:3.0, clausola:30 },
    { ruolo:"M;C", anni:24, nome:"El Aynaoui", quot:9, stip:1.8, clausola:18 },
    { ruolo:"C", anni:24, nome:"Jashari", quot:4, stip:0.8, clausola:8 },
    { ruolo:"C", anni:40, nome:"Modric", quot:20, stip:4.0, clausola:40 },
    { ruolo:"E;W", anni:23, nome:"Zalewski", quot:13, stip:2.6, clausola:26 },
    { ruolo:"C;T", anni:29, nome:"Pellegrini Lo.", quot:11, stip:2.2, clausola:22 },
    { ruolo:"T", anni:28, nome:"Vlasic", quot:14, stip:2.8, clausola:28 },
    { ruolo:"T;A", anni:27, nome:"Pulisic", quot:28, stip:5.6, clausola:56 },
    { ruolo:"T;A", anni:26, nome:"Zaniolo", quot:21, stip:4.2, clausola:42 },
    { ruolo:"T;A", anni:24, nome:"Maldini", quot:3, stip:0.6, clausola:6 },
    { ruolo:"A", anni:28, nome:"Nkunku", quot:20, stip:4.0, clausola:40 },
    { ruolo:"Pc", anni:24, nome:"Gimenez", quot:12, stip:2.4, clausola:24 },
    { ruolo:"Pc", anni:25, nome:"Kean", quot:18, stip:3.6, clausola:36 },
  ],
  "Shalpe 104": [
    { ruolo:"Por", anni:27, nome:"Martinez Jo.", quot:2, stip:0.4, clausola:4 },
    { ruolo:"Por", anni:37, nome:"Sommer", quot:16, stip:3.2, clausola:32 },
    { ruolo:"Dc", anni:28, nome:"Pongracic", quot:5, stip:1.0, clausola:10 },
    { ruolo:"Dc", anni:22, nome:"Vitik", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:26, nome:"Coco", quot:13, stip:2.6, clausola:26 },
    { ruolo:"Dc", anni:27, nome:"Lucumì", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:28, nome:"Tomori", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:37, nome:"Acerbi", quot:9, stip:1.8, clausola:18 },
    { ruolo:"Dd;Dc", anni:23, nome:"De Winter", quot:9, stip:1.8, clausola:18 },
    { ruolo:"Ds;E", anni:25, nome:"Gallo", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Ds;E", anni:28, nome:"Pezzella Giu.", quot:5, stip:1.0, clausola:10 },
    { ruolo:"E", anni:22, nome:"Wesley", quot:13, stip:2.6, clausola:26 },
    { ruolo:"E", anni:25, nome:"Cambiaso", quot:14, stip:2.8, clausola:28 },
    { ruolo:"E", anni:27, nome:"Dodò", quot:10, stip:2.0, clausola:20 },
    { ruolo:"M;C", anni:26, nome:"Fofana Y.", quot:12, stip:2.4, clausola:24 },
    { ruolo:"C", anni:24, nome:"Fagioli", quot:8, stip:1.6, clausola:16 },
    { ruolo:"E;W", anni:26, nome:"Saelemaekers", quot:20, stip:4.0, clausola:40 },
    { ruolo:"C;T", anni:26, nome:"Thorstvedt", quot:8, stip:1.6, clausola:16 },
    { ruolo:"C;T", anni:25, nome:"Ekkelenkamp", quot:10, stip:2.0, clausola:20 },
    { ruolo:"C;T", anni:36, nome:"Mkhitaryan", quot:9, stip:1.8, clausola:18 },
    { ruolo:"T;A", anni:26, nome:"Odgaard", quot:19, stip:3.8, clausola:38 },
    { ruolo:"W;A", anni:23, nome:"Santos A.", quot:8, stip:1.6, clausola:16 },
    { ruolo:"W;A", anni:20, nome:"Addai", quot:10, stip:2.0, clausola:20 },
    { ruolo:"A", anni:31, nome:"Berardi", quot:21, stip:4.2, clausola:42 },
    { ruolo:"A", anni:25, nome:"Raspadori", quot:15, stip:3.0, clausola:30 },
    { ruolo:"Pc", anni:22, nome:"Bonny", quot:14, stip:2.8, clausola:28 },
    { ruolo:"Pc", anni:26, nome:"Pinamonti", quot:16, stip:3.2, clausola:32 },
    { ruolo:"Pc", anni:28, nome:"Martinez L.", quot:34, stip:6.8, clausola:68 },
  ],
  "Finocchiona AC": [
    { ruolo:"Por", anni:28, nome:"Milinkovic-Savic V.", quot:16, stip:3.2, clausola:32 },
    { ruolo:"Por", anni:18, nome:"Pessina Mas.", quot:1, stip:0.2, clausola:2 },
    { ruolo:"Por", anni:28, nome:"Meret", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:26, nome:"Buongiorno", quot:13, stip:2.6, clausola:26 },
    { ruolo:"Dc", anni:25, nome:"Gila", quot:9, stip:1.8, clausola:18 },
    { ruolo:"Dc", anni:29, nome:"Ismajli", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:26, nome:"Hien", quot:11, stip:2.2, clausola:22 },
    { ruolo:"Ds;Dc", anni:34, nome:"Juan Jesus", quot:3, stip:0.6, clausola:6 },
    { ruolo:"Ds;Dc", anni:27, nome:"Vasquez", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Dd;Ds;E", anni:33, nome:"Marusic", quot:9, stip:1.8, clausola:18 },
    { ruolo:"B;Dd;E", anni:28, nome:"Celik", quot:13, stip:2.6, clausola:26 },
    { ruolo:"E", anni:20, nome:"Palestra", quot:16, stip:3.2, clausola:32 },
    { ruolo:"M;C", anni:31, nome:"Calhanoglu", quot:29, stip:5.8, clausola:58 },
    { ruolo:"M;C", anni:33, nome:"Freuler", quot:7, stip:1.4, clausola:14 },
    { ruolo:"C", anni:22, nome:"Sucic P.", quot:10, stip:2.0, clausola:20 },
    { ruolo:"C;T", anni:23, nome:"Taylor K.", quot:14, stip:2.8, clausola:28 },
    { ruolo:"T", anni:34, nome:"De Bruyne", quot:22, stip:4.4, clausola:44 },
    { ruolo:"W", anni:32, nome:"Politano", quot:14, stip:2.8, clausola:28 },
    { ruolo:"W;T", anni:22, nome:"Vergara", quot:6, stip:1.2, clausola:12 },
    { ruolo:"T;A", anni:28, nome:"Gudmundsson A.", quot:14, stip:2.8, clausola:28 },
    { ruolo:"W;A", anni:23, nome:"Conceicao", quot:17, stip:3.4, clausola:34 },
    { ruolo:"W;A", anni:20, nome:"Rodriguez Je.", quot:12, stip:2.4, clausola:24 },
    { ruolo:"A", anni:20, nome:"Kilicsoy", quot:16, stip:3.2, clausola:32 },
    { ruolo:"Pc", anni:24, nome:"Pellegrino M.", quot:20, stip:4.0, clausola:40 },
    { ruolo:"Pc", anni:22, nome:"Hojlund", quot:24, stip:4.8, clausola:48 },
  ],
  "Agnus Dei FC": [
    { ruolo:"Por", anni:31, nome:"Provedel", quot:17, stip:3.4, clausola:34 },
    { ruolo:"Por", anni:19, nome:"Martinelli T.", quot:1, stip:0.2, clausola:2 },
    { ruolo:"Por", anni:35, nome:"De Gea", quot:14, stip:2.8, clausola:28 },
    { ruolo:"Dc", anni:29, nome:"Luperto", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Dc", anni:30, nome:"Romagnoli", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Dc", anni:25, nome:"Solet", quot:11, stip:2.2, clausola:22 },
    { ruolo:"Dc", anni:30, nome:"Kempf", quot:11, stip:2.2, clausola:22 },
    { ruolo:"Dd;Dc", anni:25, nome:"Kalulu", quot:10, stip:2.0, clausola:20 },
    { ruolo:"Ds;E", anni:28, nome:"Martin", quot:13, stip:2.6, clausola:26 },
    { ruolo:"Ds;E", anni:25, nome:"Tavares N.", quot:6, stip:1.2, clausola:12 },
    { ruolo:"B;Ds;E", anni:32, nome:"Kolasinac", quot:7, stip:1.4, clausola:14 },
    { ruolo:"B;Dd;E", anni:26, nome:"Zappa", quot:7, stip:1.4, clausola:14 },
    { ruolo:"E", anni:31, nome:"Gosens", quot:9, stip:1.8, clausola:18 },
    { ruolo:"M;C", anni:28, nome:"Mandragora", quot:18, stip:3.6, clausola:36 },
    { ruolo:"M;C", anni:27, nome:"Locatelli", quot:13, stip:2.6, clausola:26 },
    { ruolo:"M;C", anni:31, nome:"Lobotka", quot:10, stip:2.0, clausola:20 },
    { ruolo:"C;T", anni:30, nome:"Pasalic", quot:12, stip:2.4, clausola:24 },
    { ruolo:"C;T", anni:31, nome:"Zielinski", quot:19, stip:3.8, clausola:38 },
    { ruolo:"T", anni:22, nome:"Baturina", quot:13, stip:2.6, clausola:26 },
    { ruolo:"W;T", anni:29, nome:"Vandeputte", quot:12, stip:2.4, clausola:24 },
    { ruolo:"W;A", anni:24, nome:"Isaksen", quot:14, stip:2.8, clausola:28 },
    { ruolo:"Pc", anni:26, nome:"Scamacca", quot:19, stip:3.8, clausola:38 },
    { ruolo:"Pc", anni:28, nome:"Thuram", quot:29, stip:5.8, clausola:58 },
    { ruolo:"Pc", anni:25, nome:"Krstovic", quot:15, stip:3.0, clausola:30 },
  ],
  "Wehrmacht FC": [
    { ruolo:"Por", anni:26, nome:"Svilar", quot:20, stip:4.0, clausola:40 },
    { ruolo:"Por", anni:27, nome:"Vasquez D.", quot:1, stip:0.2, clausola:2 },
    { ruolo:"Por", anni:30, nome:"Gollini", quot:1, stip:0.2, clausola:2 },
    { ruolo:"Dc", anni:31, nome:"Mina", quot:9, stip:1.8, clausola:18 },
    { ruolo:"Dc", anni:29, nome:"Mancini", quot:11, stip:2.2, clausola:22 },
    { ruolo:"Ds;Dc", anni:27, nome:"Kelly L.", quot:8, stip:1.6, clausola:16 },
    { ruolo:"Ds;Dc", anni:26, nome:"Ranieri L.", quot:7, stip:1.4, clausola:14 },
    { ruolo:"Ds;E", anni:32, nome:"Spinazzola", quot:16, stip:3.2, clausola:32 },
    { ruolo:"Ds;E", anni:31, nome:"Kamara H.", quot:7, stip:1.4, clausola:14 },
    { ruolo:"Ds;E", anni:27, nome:"Valeri", quot:10, stip:2.0, clausola:20 },
    { ruolo:"B;Dd;E", anni:22, nome:"Rensch", quot:6, stip:1.2, clausola:12 },
    { ruolo:"E", anni:25, nome:"Joao Mario", quot:7, stip:1.4, clausola:14 },
    { ruolo:"E", anni:28, nome:"Angelino", quot:7, stip:1.4, clausola:14 },
    { ruolo:"E", anni:26, nome:"Zortea", quot:8, stip:1.6, clausola:16 },
    { ruolo:"M;C", anni:34, nome:"De Roon", quot:13, stip:2.6, clausola:26 },
    { ruolo:"C", anni:24, nome:"Bernabè", quot:16, stip:3.2, clausola:32 },
    { ruolo:"C", anni:31, nome:"Hernani", quot:6, stip:1.2, clausola:12 },
    { ruolo:"C", anni:21, nome:"Pisilli", quot:7, stip:1.4, clausola:14 },
    { ruolo:"C;T", anni:29, nome:"Loftus-Cheek", quot:9, stip:1.8, clausola:18 },
    { ruolo:"C;T", anni:30, nome:"Rabiot", quot:23, stip:4.6, clausola:46 },
    { ruolo:"C;T", anni:22, nome:"Fazzini", quot:4, stip:0.8, clausola:8 },
    { ruolo:"W", anni:33, nome:"El Shaarawy", quot:7, stip:1.4, clausola:14 },
    { ruolo:"W;T", anni:22, nome:"Rowe", quot:14, stip:2.8, clausola:28 },
    { ruolo:"W;A", anni:28, nome:"Strefezza", quot:10, stip:2.0, clausola:20 },
    { ruolo:"W;A", anni:28, nome:"Neres", quot:15, stip:3.0, clausola:30 },
    { ruolo:"A", anni:22, nome:"Soulè", quot:25, stip:5.0, clausola:50 },
    { ruolo:"A", anni:26, nome:"Leao", quot:24, stip:4.8, clausola:48 },
    { ruolo:"Pc", anni:21, nome:"Ferguson E.", quot:19, stip:3.8, clausola:38 },
  ],
};

export const OBJECTIVES = {
  "Alcool Campi": {
    allenatore: [
      { testo: "Mantieni almeno 12 giocatori della rosa iniziale fino a fine stagione.", progresso: "✗", guadagno: -2 },
      { testo: "Non scendere mai sotto i 10M di saldo per più di 2 giornate consecutive.", progresso: "0/3", guadagno: null },
      { testo: "Mantieni il salary cap sempre sotto i 72M.", progresso: "70.8", guadagno: null },
    ],
    ds: [],
    dg: [],
    investimenti: [
      { costo: 8, testo: "Clausola No-Svincolo", note: "Jonathan David", progresso: "16 pres, 4 gol, 1 ass", guadagno: 5.2 },
      { costo: 5, testo: "Vice Allenatore Premium", note: "", progresso: "▣▣▢", guadagno: null },
      { costo: 1, testo: "Scommessa Rendimento", note: "Zerbin", progresso: "4.0", guadagno: null },
      { costo: 1, testo: "Scommessa Rendimento", note: "Iker Bravo", progresso: "Impossibile", guadagno: 0 },
      { costo: 10, testo: "Ristrutturazione Stadio", note: "", progresso: "-", guadagno: null },
    ],
  },
  "Borjcellona": {
    allenatore: [
      { testo: "Effettua almeno 7 operazioni di mercato tra presidenti.", progresso: "✓", guadagno: 5 },
      { testo: "Raggiungi almeno 85M complessivi da premi partita e bonus allenatore.", progresso: "107", guadagno: 5 },
      { testo: "Ottieni almeno 4,5M netti in 8 giornate.", progresso: "8/8", guadagno: null },
    ],
    ds: [],
    dg: [],
    investimenti: [
      { costo: 8, testo: "Clausola No-Svincolo", note: "Riccardo Orsolini", progresso: "-", guadagno: 6.9 },
      { costo: 5, testo: "Vice Allenatore Premium", note: "", progresso: "1/3", guadagno: null },
      { costo: 10, testo: "Ristrutturazione Stadio", note: "Attivo dal 1/8/2026", progresso: "-", guadagno: null },
    ],
  },
  "Balillareal": {
    allenatore: [
      { testo: "Gli Under 21 devono segnare almeno 8 gol complessivi.", progresso: "8/8", guadagno: null },
      { testo: "Realizza almeno 15M di plusvalenza netta su max 3 cessioni.", progresso: "-", guadagno: null },
      { testo: "Chiudi la stagione con un attaccante da oltre 15 gol.", progresso: "-", guadagno: null },
    ],
    ds: [],
    dg: [],
    investimenti: [
      { costo: 8, testo: "Clausola No-Svincolo", note: "McTominay", progresso: "-", guadagno: null },
      { costo: 5, testo: "Vice Allenatore Premium", note: "", progresso: "3/3", guadagno: null },
    ],
  },
  "AK Toio": {
    allenatore: [
      { testo: "Almeno 2 Under 21 devono totalizzare insieme 25 presenze.", progresso: "✓", guadagno: 5 },
      { testo: "Per almeno 19 giornate mantieni una rosa di almeno 28 giocatori.", progresso: "✓", guadagno: 5 },
      { testo: "Acquista uno svincolato con quotazione < 6 e schieralo per almeno 8 giornate.", progresso: "✓ (Hermoso)", guadagno: 10 },
    ],
    ds: [],
    dg: [],
    investimenti: [
      { costo: 8, testo: "Clausola No-Svincolo", note: "Moise Kean", progresso: "-", guadagno: null },
      { costo: 2, testo: "Scouting Estero", note: "Robert Lewandoski", progresso: "-", guadagno: null },
    ],
  },
  "Shalpe 104": {
    allenatore: [
      { testo: "Ottieni almeno 12 bonus 'Porta Inviolata'.", progresso: "12/12", guadagno: 5 },
      { testo: "Non effettuare più di 2 svincoli ordinari in stagione.", progresso: "1/2", guadagno: null },
      { testo: "Massimo 1 penalità per svincolo e nessuna altra sanzione.", progresso: "-", guadagno: -2 },
    ],
    ds: [],
    dg: [],
    investimenti: [
      { costo: 8, testo: "Clausola No-Svincolo", note: "Lautaro Martinez", progresso: "Completato", guadagno: null },
      { costo: 5, testo: "Vice Allenatore Premium", note: "", progresso: "1/3", guadagno: null },
      { costo: 1, testo: "Scommessa Rendimento", note: "Sulemana", progresso: "Impossibile", guadagno: null },
      { costo: 1, testo: "Scommessa Rendimento", note: "Martinez Jo.", progresso: "-", guadagno: null },
      { costo: 10, testo: "Ristrutturazione Stadio", note: "", progresso: "-", guadagno: null },
    ],
  },
  "Finocchiona AC": {
    allenatore: [
      { testo: "Mantieni almeno 12 giocatori della rosa iniziale fino a fine stagione.", progresso: "-", guadagno: null },
      { testo: "Raggiungi almeno 85M complessivi da premi partita e bonus allenatore.", progresso: "92.3", guadagno: null },
      { testo: "Saldo finale >25M e non più di 3 gol segnati in più di 5 giornate.", progresso: "5/5", guadagno: null },
    ],
    ds: [],
    dg: [],
    investimenti: [
      { costo: 15, testo: "Abbonamenti Premium", note: "", progresso: "-", guadagno: 9 },
      { costo: 10, testo: "Ristrutturazione Stadio", note: "", progresso: "-", guadagno: null },
    ],
  },
  "Agnus Dei FC": {
    allenatore: [
      { testo: "Se investi almeno 5M, ricava almeno il 150% in guadagni diretti.", progresso: "-", guadagno: null },
      { testo: "Realizza almeno 15M di plusvalenza netta su max 3 cessioni.", progresso: "-", guadagno: null },
      { testo: "Chiudi con saldo <5M senza mai andare in negativo.", progresso: "-", guadagno: null },
    ],
    ds: [],
    dg: [],
    investimenti: [
      { costo: 8, testo: "Clausola No-Svincolo", note: "Marcus Thuram", progresso: "-", guadagno: null },
    ],
  },
  "Wehrmacht FC": {
    allenatore: [
      { testo: "Effettua almeno 7 operazioni di mercato tra presidenti.", progresso: "-", guadagno: 5 },
      { testo: "Per almeno 19 giornate, mantieni una rosa di almeno 28 giocatori.", progresso: "-", guadagno: null },
      { testo: "Finisci tra le prime 3 per modificatore difesa.", progresso: "-", guadagno: null },
    ],
    ds: [],
    dg: [],
    investimenti: [],
  },
};

export const CLUB_IDENTITY = {
  "Alcool Campi": {
    campionati: "-", coppe: "-", supercoppe: "-",
    fondazione: "2023",
    stadio: "La Birreria (capacità 42.000)",
    rivali: "Balillareal, Shalpe 104",
    gemellato: null,
    descrizione: `Nata nel 2023 dalle ceneri della leggendaria Mignottingham Forest, Alcool Campi è rinata con spirito goliardico e ambizione feroce. Dopo due secondi posti consecutivi (2024 e 2025), il club punta con decisione al suo primo scudetto.\n\nGuidata da una dirigenza spregiudicata e da una filosofia di gioco offensiva, la squadra combina talento e imprevedibilità, con uno spogliatoio famoso per i festeggiamenti infiniti. Il nuovo formato a 8 squadre segna una sfida storica: più rivali, più spettacolo, più possibilità di gloria.\n\nSostenuta dalla fedele Curva degli Spiriti, Alcool Campi è pronta a scrivere la propria leggenda.`,
    motto: `"Non vinciamo sempre, ma quando lo facciamo, non ricordiamo nulla."`,
  },
  "Borjcellona": {
    campionati: "1", coppe: "-", supercoppe: "-",
    fondazione: "2023",
    stadio: "Tao Nou (capacità 80.000 con Skybox)",
    rivali: "AK Toio, Balillareal, Wehrmacht FC",
    gemellato: "Agnus Dei FC",
    descrizione: `Fondata nel 2023 col nome di Omega Team, ha subito dato spettacolo ai propri tifosi vincendo il Campionato alla sua prima edizione.\n\nIl 2024/25 è stato un anno amaro che ci ha visto concludere a 3 punti dal Titolo, ma con un nuovo spirito e una nuova identità il club è pronto a mettersi alla prova in una nuova competizione a 8 giocatori.\n\nIl BORJCELLONA è pronto e lo dimostrerà.`,
    motto: null,
  },
  "Balillareal": {
    campionati: "1", coppe: "-", supercoppe: "-",
    fondazione: "2022",
    stadio: "I Bilaghi (capacità 70.000 + negozio Bilaghi elettrodomestici)",
    rivali: "Odio indistinto erga omnes",
    gemellato: null,
    descrizione: `Fondata nel 2022 sulle ceneri della mai vittoriosa AC DENTIACRISTO, si è subito distinta per spirito combattivo e patriottismo.\n\nDopo aver sfiorato i trofei nel primo anno e conquistato lo scudetto nel secondo, l'annata 25/26 porta grandi cambiamenti: stemma nuovo, divisa nuova, nuovo DS e una squadra di campioni giovani e volenterosi. DEI VERI GIOVANI BALILLA.`,
    motto: "AMOR PATRIAE NOSTRA LEX · MEMENTO AUDERE SEMPER · POST FATA, RESURGO",
  },
  "AK Toio": {
    campionati: "-", coppe: "-", supercoppe: "-",
    fondazione: "-",
    stadio: "-",
    rivali: "Borjcellona",
    gemellato: null,
    descrizione: "Descrizione non ancora inserita.",
    motto: null,
  },
  "Shalpe 104": {
    campionati: "-", coppe: "-", supercoppe: "-",
    fondazione: "2025",
    stadio: "Centro Didattico Morgagni (5.000 posti + Mensa inclusa)",
    rivali: "Balillareal, Alcool Campi, Wehrmacht FC",
    gemellato: null,
    descrizione: `Nati dalle ceneri del DINAMO 104, dopo l'acquisto del presidente DANDANDANDAN, non siamo qui per scherzare, ma nemmeno per annoiarvi. Siamo gli SHALPE 104, e se c'è una cosa che abbiamo imparato, è che la gloria non si compra al supermercato.\n\nLa nostra filosofia: serietà sul campo, sorrisi fuori. La nostra tattica si chiama "attacco a tradimento": un mix letale di statistiche scientifiche e pura, folle intuizione.\n\nIl nostro stadio, il Centro Didattico Morgagni, non è un luogo, ma un'emozione. Qui, tra una risata e una bestemmia, celebriamo il nostro credo calcistico.`,
    motto: `"Non si molla un cazzo."`,
  },
  "Finocchiona AC": {
    campionati: "-", coppe: "-", supercoppe: "-",
    fondazione: "2022",
    stadio: "Teatro Ariston (capacità 5.000)",
    rivali: "Balillareal, Agnus Dei FC",
    gemellato: "Borjcellona",
    descrizione: `Fondata nel 2022 a San Remo, parte dalla Lega PRO con una rosa composta solo da artisti in gara al Festival della Musica Italiana, possibilmente di orientamento omosessuale.\n\nIl principale sponsor è N*groni, celebre marchio di affettati. La società mantiene l'impegno di tutelare le diversità come nell'anno di fondazione.\n\nAlcune frasi del presidente ilmari: "Degli under21 non ce ne frega un topocazzo"`,
    motto: null,
  },
  "Agnus Dei FC": {
    campionati: "-", coppe: "-", supercoppe: "-",
    fondazione: "-",
    stadio: "-",
    rivali: "Finocchiona AC",
    gemellato: "Borjcellona",
    descrizione: "Descrizione non ancora inserita.",
    motto: null,
  },
  "Wehrmacht FC": {
    campionati: "-", coppe: "-", supercoppe: "-",
    fondazione: "-",
    stadio: "-",
    rivali: "-",
    gemellato: null,
    descrizione: "Descrizione non ancora inserita.",
    motto: null,
  },
};

export const MOVEMENTS = {
  "Alcool Campi": [
    { data: "01/08/25", desc: "Risoluzione Contratto Strefezza", entrata: 6.5, uscita: null },
    { data: "05/08/25", desc: "Acquisto Nicoló Rovella da svincolati", entrata: null, uscita: 10.75 },
    { data: "07/08/25", desc: "Acquisto Morten Frendrup da svincolati", entrata: null, uscita: 9.1 },
    { data: "10/08/25", desc: "Acquisto Charles De Ketelaere da Maro", entrata: null, uscita: 21.0 },
    { data: "10/08/25", desc: "Cessione Albert Gudmundsson a Maro", entrata: 22.0, uscita: null },
    { data: "10/08/25", desc: "Acquisto Ondrejka da svincolati", entrata: null, uscita: 7.6 },
  ],
  "Borjcellona": [
    { data: "05/08/25", desc: "Cessione Frattesi a Dani", entrata: 12.0, uscita: null },
    { data: "09/08/25", desc: "Acquisto Perin da svincolati", entrata: null, uscita: 0.5 },
    { data: "09/08/25", desc: "Acquisto McKennie da Maro", entrata: null, uscita: 9.5 },
    { data: "09/08/25", desc: "Cessione Neres a Maro", entrata: 12.0, uscita: null },
    { data: "10/08/25", desc: "Acquisto Konè I. da svincolati", entrata: null, uscita: 3.5 },
    { data: "10/08/25", desc: "Cessione Yildiz ad Albe", entrata: 23.0, uscita: null },
  ],
  "Balillareal": [
    { data: "03/08/25", desc: "Risoluzione Contratto Yerry Mina", entrata: 3.5, uscita: null },
    { data: "06/08/25", desc: "Acquisto Ghilardi da svincolati", entrata: null, uscita: 3.8 },
    { data: "09/08/25", desc: "Acquisto Marianucci da svincolati", entrata: null, uscita: 1.5 },
    { data: "10/08/25", desc: "Acquisto Ramon da svincolati", entrata: null, uscita: 2.0 },
    { data: "12/08/25", desc: "Acquisto Skorupski da Fanfa", entrata: null, uscita: 7.0 },
  ],
  "AK Toio": [
    { data: "10/08/25", desc: "Cessione Yildiz a Borgio", entrata: 23.0, uscita: null },
    { data: "10/08/25", desc: "Acquisto Jimenez da Maro", entrata: null, uscita: 4.0 },
    { data: "10/08/25", desc: "Cessione Olivera a Maro", entrata: 5.5, uscita: null },
    { data: "11/08/25", desc: "Acquisto Terracciano da svincolati", entrata: null, uscita: 0.5 },
    { data: "15/08/25", desc: "Acquisto Max Allegri (allenatore)", entrata: null, uscita: 7.8 },
    { data: "17/08/25", desc: "Cessione Jashari ad Albe", entrata: null, uscita: null },
  ],
  "Shalpe 104": [
    { data: "05/08/25", desc: "Acquisto Frattesi da Borgio", entrata: null, uscita: 12.0 },
    { data: "10/08/25", desc: "Acquisto Thorstvedt da svincolati", entrata: null, uscita: 4.0 },
    { data: "10/08/25", desc: "Acquisto Ekkelenkamp da svincolati", entrata: null, uscita: 6.1 },
    { data: "15/08/25", desc: "Pagamento 5€ extra budget", entrata: 12.5, uscita: null },
  ],
  "Finocchiona AC": [
    { data: "06/08/25", desc: "Acquisto McKennie da svincolati", entrata: null, uscita: 9.0 },
    { data: "09/08/25", desc: "Acquisto Neres da Borgio", entrata: null, uscita: 12.0 },
    { data: "09/08/25", desc: "Cessione McKennie a Borgio", entrata: 9.5, uscita: null },
    { data: "10/08/25", desc: "Cessione De Ketelaere a Raspa", entrata: 21.0, uscita: null },
    { data: "10/08/25", desc: "Acquisto De Ketelaere da Raspa", entrata: null, uscita: 21.0 },
  ],
  "Agnus Dei FC": [
    { data: "12/08/25", desc: "Cessione Skorupski a Pippo", entrata: 7.0, uscita: null },
    { data: "12/08/25", desc: "Risoluzione Contratto Thauvin", entrata: 8.0, uscita: null },
    { data: "12/08/25", desc: "Risoluzione Contratto Man", entrata: 5.5, uscita: null },
    { data: "16/08/25", desc: "Pagamento 5€ extra budget", entrata: 12.5, uscita: null },
  ],
  "Wehrmacht FC": [
    { data: "11/08/25", desc: "Cessione Milinkovic-Savic a Maro", entrata: 2.0, uscita: null },
    { data: "13/08/25", desc: "Risoluzione contratto Ndoye", entrata: 9.0, uscita: null },
    { data: "13/08/25", desc: "Pagamento 5€ extra budget", entrata: 12.5, uscita: null },
    { data: "17/08/25", desc: "Acquisto Vasquez da svincolati", entrata: null, uscita: 0.5 },
    { data: "18/08/25", desc: "Cessione Di Lorenzo a Maro", entrata: 10.5, uscita: null },
  ],
};

export const CLUB_INFO = {
  "Alcool Campi": {
    fondazione: "2023",
    stadio: "La Birreria",
    capacita: "42.000",
    rivali: "Balillareal, Shalpe 104",
    gemellato: null,
    campionati: 0,
    coppe: 0,
    supercoppe: 0,
    descrizione: `Nata nel 2023 dalle ceneri della leggendaria Mignottingham Forest, Alcool Campi è rinata con spirito goliardico e ambizione feroce. Dopo due secondi posti consecutivi (2024 e 2025), il club punta con decisione al suo primo scudetto.

Guidata da una dirigenza spregiudicata e da una filosofia di gioco offensiva, la squadra combina talento e imprevedibilità, con uno spogliatoio famoso per i festeggiamenti infiniti. Il nuovo formato a 8 squadre segna una sfida storica: più rivali, più spettacolo, più possibilità di gloria.

Sostenuta dalla fedele Curva degli Spiriti, Alcool Campi è pronta a scrivere la propria leggenda.`,
    motto: "Non vinciamo sempre, ma quando lo facciamo, non ricordiamo nulla.",
  },
  "Borjcellona": {
    fondazione: "2023",
    stadio: "Tao Nou",
    capacita: "80.000",
    rivali: "AK Toio, Balillareal, Wehrmacht FC",
    gemellato: "Agnus Dei FC",
    campionati: 1,
    coppe: 0,
    supercoppe: 0,
    descrizione: `Fondata nel 2023 col nome di Omega Team, ha subito dato spettacolo ai propri tifosi vincendo il Campionato alla sua prima edizione.

Il 2024/25 è stato un anno amaro che ci ha visto concludere a 3 punti dal Titolo, ma con un nuovo spirito e una nuova identità il club è pronto a mettersi alla prova in una nuova competizione a 8 giocatori.

Il BORJCELLONA è pronto e lo dimostrerà.`,
    motto: null,
  },
  "Balillareal": {
    fondazione: "2022",
    stadio: "I Bilaghi",
    capacita: "70.000",
    rivali: "Odio indistinto erga omnes",
    gemellato: null,
    campionati: 1,
    coppe: 0,
    supercoppe: 0,
    descrizione: `Fondata nel lontano 2022 sulle ceneri della mai vittoriosa AC DENTIACRISTO, ha subito dato grattacapi alle avversarie distinguendosi per spirito combattivo e patriottismo.

Il primo anno dopo il re-branding la squadra sfiorò i trofei, cadendo per via dei continui infortuni e della discontinuità di alcuni giocatori — condannati alla damnatio memoriae l'anno successivo.

L'anno successivo ci siamo fatti valere e abbiamo portato a casa lo scudetto tanto meritato. L'annata 25/26 porta stemma nuovo, divisa nuova, il nuovo DS Rebecca aka "Ante Rebic" Gallo e una squadra di giovani campioni. DEI VERI GIOVANI BALILLA.`,
    motto: "AMOR PATRIAE NOSTRA LEX",
  },
  "AK Toio": {
    fondazione: "-",
    stadio: "-",
    capacita: "-",
    rivali: "-",
    gemellato: null,
    campionati: 0,
    coppe: 0,
    supercoppe: 0,
    descrizione: "Descrizione non ancora inserita.",
    motto: null,
  },
  "Shalpe 104": {
    fondazione: "2025",
    stadio: "Centro Didattico Morgagni",
    capacita: "5.000",
    rivali: "Balillareal, Alcool Campi, Wehrmacht FC",
    gemellato: null,
    campionati: 0,
    coppe: 0,
    supercoppe: 0,
    descrizione: `Nati dalle ceneri del DINAMO 104, dopo l'acquisto del presidente DANDANDANDAN, non siamo qui per scherzare, ma nemmeno per annoiarvi. Siamo gli SHALPE 104, e se c'è una cosa che abbiamo imparato, è che la gloria non si compra al supermercato.

La nostra filosofia è chiara: serietà sul campo, sorrisi fuori. La nostra tattica si chiama "attacco a tradimento": un mix letale di statistiche scientifiche e pura, folle intuizione.

Il nostro stadio, il Centro Didattico Morgagni, non è un luogo, ma un'emozione. Qui, tra una risata e una bestemmia, celebriamo il nostro credo calcistico.`,
    motto: "Non si molla un cazzo.",
  },
  "Finocchiona AC": {
    fondazione: "2022",
    stadio: "Teatro Ariston",
    capacita: "5.000",
    rivali: "Balillareal, Agnus Dei FC",
    gemellato: "Borjcellona",
    campionati: 0,
    coppe: 0,
    supercoppe: 0,
    descrizione: `Fondata nel 2022 a San Remo in Liguria, questa squadra parte dalla Lega PRO con una rosa composta solo da artisti in gara al Festival della Musica Italiana di San Remo. La fama dei giocatori ha gradualmente attratto sponsor fino a potersi permettere la massima serie.

Il principale sponsor è N*groni, celebre marchio di affettati che ha deciso di iniziare a produrre la Finocchiona per onorare la squadra sostenuta.

La società mantiene l'impegno di tutelare le diversità come nell'anno di fondazione, con una rosa che presenta esponenti di molte minoranze.`,
    motto: "Degli under21 non ce ne frega un topocazzo.",
  },
  "Agnus Dei FC": {
    fondazione: "-",
    stadio: "-",
    capacita: "-",
    rivali: "-",
    gemellato: "Borjcellona",
    campionati: 0,
    coppe: 0,
    supercoppe: 0,
    descrizione: "Descrizione non ancora inserita.",
    motto: null,
  },
  "Wehrmacht FC": {
    fondazione: "-",
    stadio: "-",
    capacita: "-",
    rivali: "-",
    gemellato: null,
    campionati: 0,
    coppe: 0,
    supercoppe: 0,
    descrizione: "Descrizione non ancora inserita.",
    motto: null,
  },
};
export const FREE_AGENTS = [
  { ruolo:"A", anni:27, nome:"Laurientè", quot:21.0, stip:4.2, clausola:42.0, fuoriLista:false },
  { ruolo:"A", anni:28, nome:"Bonazzoli", quot:20.0, stip:4.0, clausola:40.0, fuoriLista:false },
  { ruolo:"Pc", anni:27, nome:"Castellanos", quot:18.0, stip:3.6, clausola:36.0, fuoriLista:true },
  { ruolo:"W", anni:25, nome:"Ndoye", quot:18.0, stip:3.6, clausola:36.0, fuoriLista:true },
  { ruolo:"Pc", anni:30, nome:"Simeone", quot:18.0, stip:3.6, clausola:36.0, fuoriLista:false },
  { ruolo:"A", anni:32, nome:"Moreo", quot:17.0, stip:3.4, clausola:34.0, fuoriLista:false },
  { ruolo:"A", anni:22, nome:"Giovane", quot:16.0, stip:3.2, clausola:32.0, fuoriLista:false },
  { ruolo:"A", anni:32, nome:"Thauvin", quot:16.0, stip:3.2, clausola:32.0, fuoriLista:true },
  { ruolo:"Pc", anni:38, nome:"Vardy", quot:16.0, stip:3.2, clausola:32.0, fuoriLista:false },
  { ruolo:"M;C", anni:31, nome:"Cataldi", quot:15.0, stip:3.0, clausola:30.0, fuoriLista:false },
  { ruolo:"Pc", anni:23, nome:"Colombo", quot:15.0, stip:3.0, clausola:30.0, fuoriLista:false },
  { ruolo:"Por", anni:30, nome:"Falcone", quot:15.0, stip:3.0, clausola:30.0, fuoriLista:false },
  { ruolo:"A", anni:28, nome:"Lookman", quot:15.0, stip:3.0, clausola:30.0, fuoriLista:true },
  { ruolo:"C;T", anni:29, nome:"Thorsby", quot:15.0, stip:3.0, clausola:30.0, fuoriLista:false },
  { ruolo:"C;T", anni:25, nome:"Caqueret", quot:14.0, stip:2.8, clausola:28.0, fuoriLista:false },
  { ruolo:"M;C", anni:29, nome:"Coulibaly L.", quot:14.0, stip:2.8, clausola:28.0, fuoriLista:false },
  { ruolo:"Pc", anni:22, nome:"Durosinmi", quot:14.0, stip:2.8, clausola:28.0, fuoriLista:false },
  { ruolo:"C;W", anni:34, nome:"Messias", quot:14.0, stip:2.8, clausola:28.0, fuoriLista:false },
  { ruolo:"Dc", anni:26, nome:"Ostigard", quot:14.0, stip:2.8, clausola:28.0, fuoriLista:false },
  { ruolo:"M;C", anni:24, nome:"Ricci S.", quot:14.0, stip:2.8, clausola:28.0, fuoriLista:false },
  { ruolo:"Pc", anni:25, nome:"Vitinha O.", quot:14.0, stip:2.8, clausola:28.0, fuoriLista:false },
  { ruolo:"W;A", anni:23, nome:"Cancellieri", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:false },
  { ruolo:"Por", anni:24, nome:"Corvi", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:false },
  { ruolo:"Pc", anni:32, nome:"Fullkrug", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:false },
  { ruolo:"C", anni:26, nome:"Guendouzi", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:true },
  { ruolo:"A", anni:26, nome:"Lang", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:true },
  { ruolo:"M;C", anni:30, nome:"Mazzitelli", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:false },
  { ruolo:"Pc", anni:22, nome:"Ratkov", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:false },
  { ruolo:"W;T", anni:25, nome:"Tramoni M.", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:false },
  { ruolo:"T;A", anni:36, nome:"Vazquez", quot:13.0, stip:2.6, clausola:26.0, fuoriLista:true },
  { ruolo:"Por", anni:28, nome:"Audero", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"W;A", anni:24, nome:"Banda", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"Pc", anni:25, nome:"Borrelli", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"C;T", anni:25, nome:"Brescianini", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"Por", anni:24, nome:"Caprile", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"Pc", anni:28, nome:"Dovbyk", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"T", anni:25, nome:"Gaetano", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"E;W", anni:33, nome:"Kostic", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"C;T", anni:22, nome:"Miretti", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"A", anni:38, nome:"Pedro", quot:12.0, stip:2.4, clausola:24.0, fuoriLista:false },
  { ruolo:"A", anni:31, nome:"Ekuban", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:false },
  { ruolo:"C;W", anni:23, nome:"Ellertsson", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:false },
  { ruolo:"W;A", anni:27, nome:"Gonzalez N.", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:true },
  { ruolo:"Dc", anni:34, nome:"Kabasele", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:false },
  { ruolo:"W;A", anni:27, nome:"Man", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:true },
  { ruolo:"Por", anni:29, nome:"Montipò", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:false },
  { ruolo:"Por", anni:26, nome:"Okoye", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:false },
  { ruolo:"T", anni:23, nome:"Samardzic", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:false },
  { ruolo:"W;A", anni:26, nome:"Sottil", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:false },
  { ruolo:"A", anni:23, nome:"Sulemana K.", quot:11.0, stip:2.2, clausola:22.0, fuoriLista:false },
  { ruolo:"C", anni:29, nome:"Basic", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"C;T", anni:22, nome:"Berisha M.", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"Por", anni:27, nome:"Bijlow", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:32, nome:"Di Lorenzo", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"A", anni:19, nome:"Ekhator", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"W", anni:24, nome:"Fadera", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"W", anni:29, nome:"Harrison", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"W", anni:27, nome:"Leris", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"Por", anni:27, nome:"Muric", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"Pc", anni:29, nome:"Nzola", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"Dd;Ds;E", anni:22, nome:"Terracciano F.", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"W;T", anni:22, nome:"Volpato", quot:10.0, stip:2.0, clausola:20.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:23, nome:"Belghali", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"Dc", anni:22, nome:"Circati", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"W", anni:24, nome:"Felici", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"C;T", anni:25, nome:"Gandelman", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"M;C", anni:30, nome:"Karlstrom", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"Por", anni:32, nome:"Leali", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"M;C", anni:37, nome:"Matic", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:33, nome:"Moreno Alb.", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"A", anni:25, nome:"Ngonge", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:true },
  { ruolo:"A", anni:26, nome:"Noslin", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"Por", anni:33, nome:"Paleari", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:29, nome:"Pavard", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:true },
  { ruolo:"Dd;Dc", anni:28, nome:"Posch", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:true },
  { ruolo:"C", anni:28, nome:"Serdar", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"Dc", anni:21, nome:"Tiago Gabriel", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:21, nome:"Valle", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:25, nome:"Zanoli", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"W", anni:26, nome:"Zhegrova", quot:9.0, stip:1.8, clausola:18.0, fuoriLista:false },
  { ruolo:"A", anni:25, nome:"Benedyczak", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:true },
  { ruolo:"C", anni:26, nome:"Bernede", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"Pc", anni:29, nome:"Buksa", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"B;Ds;E", anni:24, nome:"Cabal", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"W;T", anni:26, nome:"Elmas", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"C;T", anni:22, nome:"Fabbian", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"C;T", anni:27, nome:"Folorunsho", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"M;C", anni:31, nome:"Gagliardini", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:20, nome:"Idrissi R.", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"Dc", anni:25, nome:"Idzes", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"M;C", anni:25, nome:"Loyola", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"M;C", anni:27, nome:"Moro N.", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"W;A", anni:25, nome:"N'Dri", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"Ds;Dc", anni:23, nome:"Obert", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"W;A", anni:24, nome:"Pierotti", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"M;C", anni:26, nome:"Pobega", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:24, nome:"Tchatchoua", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:true },
  { ruolo:"Pc", anni:18, nome:"Vaz", quot:8.0, stip:1.6, clausola:16.0, fuoriLista:false },
  { ruolo:"M;C", anni:25, nome:"Adopo", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"C", anni:28, nome:"Aebischer", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Dd;Ds;E", anni:23, nome:"Barbieri", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Dc", anni:22, nome:"Bertola", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"A", anni:23, nome:"Bowie", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Dd;Ds;E", anni:19, nome:"Britschgi", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"E", anni:37, nome:"Cuadrado", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Dc", anni:23, nome:"Folino", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"A", anni:27, nome:"Johnsen", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:true },
  { ruolo:"Dc", anni:19, nome:"Leoni", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:true },
  { ruolo:"Dc", anni:23, nome:"Marcandalli", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Pc", anni:26, nome:"Mosquera", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Dc", anni:22, nome:"Muharemovic", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:21, nome:"Obrador", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Pc", anni:24, nome:"Piccoli", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"C", anni:28, nome:"Piotrowski", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"M;C", anni:29, nome:"Ramadani", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Por", anni:27, nome:"Semper", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"C", anni:23, nome:"Sorensen O.", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"E;W", anni:25, nome:"Weah", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:true },
  { ruolo:"Pc", anni:34, nome:"Zapata D.", quot:7.0, stip:1.4, clausola:14.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:21, nome:"Athekame", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"T;A", anni:22, nome:"Baldanzi", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Pc", anni:32, nome:"Belotti", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"A", anni:24, nome:"Beltran L.", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:true },
  { ruolo:"Dc", anni:35, nome:"Caracciolo A.", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Pc", anni:27, nome:"Cheddira", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Pc", anni:27, nome:"Cutrone", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:true },
  { ruolo:"Pc", anni:25, nome:"Dallinga", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Pc", anni:35, nome:"Djuric", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:27, nome:"Frese", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"B;Ds;E", anni:29, nome:"Garcia U.", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"M;C", anni:24, nome:"Gilmour", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:24, nome:"Kossounou", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"W;A", anni:25, nome:"Kuhn", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Pc", anni:22, nome:"Meister", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"M;C", anni:19, nome:"Miller L.", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"C;W", anni:23, nome:"Musah", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"M;C", anni:21, nome:"Ndour", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"A", anni:20, nome:"Njie", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Pc", anni:25, nome:"Openda", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"W;T;A", anni:23, nome:"Oristanio", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"E", anni:25, nome:"Parisi", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"C", anni:27, nome:"Payero", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"M;C", anni:22, nome:"Prati", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Pc", anni:29, nome:"Sanabria", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"A", anni:37, nome:"Sanchez", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:true },
  { ruolo:"M;C", anni:22, nome:"Sulemana I.", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Por", anni:23, nome:"Suzuki", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"Pc", anni:24, nome:"Tourè E.", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:true },
  { ruolo:"Dc", anni:26, nome:"Valenti", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:false },
  { ruolo:"M;C", anni:34, nome:"Vecino", quot:6.0, stip:1.2, clausola:12.0, fuoriLista:true },
  { ruolo:"C;T", anni:21, nome:"Akinsanmiro", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Dc", anni:32, nome:"Bianchetti", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"M;C", anni:22, nome:"Bondo", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:26, nome:"Bradaric", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Dc", anni:25, nome:"Canestrelli", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Dc", anni:25, nome:"Edmundsson", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"C;T", anni:26, nome:"Ferguson", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"W;T", anni:27, nome:"Harroui", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"C", anni:24, nome:"Iannoni", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"E;W", anni:22, nome:"Iling Junior", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Dd;Ds;E", anni:20, nome:"Jimenez A.", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:29, nome:"Lazaro", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"M;C", anni:20, nome:"Lipani", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"T", anni:19, nome:"Lorran", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Pc", anni:25, nome:"Lucca", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:true },
  { ruolo:"M;C", anni:24, nome:"Masini", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"M;C", anni:25, nome:"Nicolussi Caviglia", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Dc", anni:22, nome:"Troilo", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:23, nome:"Veiga D.", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:25, nome:"Walukiewicz", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"Dc", anni:28, nome:"Zè Pedro", quot:5.0, stip:1.0, clausola:10.0, fuoriLista:false },
  { ruolo:"M;C", anni:33, nome:"Akpa Akpro", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:20, nome:"Amorim", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Dc", anni:24, nome:"Bella-Kotchap", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"A", anni:20, nome:"Bravo", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"B;Dd;E", anni:29, nome:"Calabresi", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"T;A", anni:20, nome:"Carboni V.", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"Dc", anni:33, nome:"De Vrij", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:30, nome:"Deiola", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Pc", anni:29, nome:"Dia", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"C", anni:22, nome:"Diouf", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"W;A", anni:22, nome:"Dominguez B.", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:30, nome:"Estevez", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"E", anni:19, nome:"Fortini", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"C;T", anni:26, nome:"Frattesi", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:25, nome:"Ghion", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"C", anni:21, nome:"Gineitis", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:30, nome:"Grassi", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"C;T", anni:21, nome:"Ilkhan", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Pc", anni:35, nome:"Immobile", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"C;T", anni:27, nome:"Koopmeiners", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Pc", anni:26, nome:"Kulenovic", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Pc", anni:23, nome:"Lind", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"M;C", anni:27, nome:"Maleh", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:27, nome:"Marin M.", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Pc", anni:25, nome:"Mulattieri", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"Dc", anni:27, nome:"Nelsson", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:25, nome:"Niasse", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"A", anni:25, nome:"Okafor", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"Ds;E", anni:28, nome:"Olivera", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:21, nome:"Ordonez C.", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:25, nome:"Pedersen", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:26, nome:"Pellegrini Lu.", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"E;M", anni:24, nome:"Piccinini G.", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"M;C", anni:24, nome:"Rovella", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"A", anni:24, nome:"Sarr A.", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"B;Dd;E", anni:22, nome:"Savona", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"M;C", anni:33, nome:"Sergi Roberto", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:25, nome:"Smolcic I.", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"C", anni:24, nome:"Sohm", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Pc", anni:25, nome:"Stojilkovic", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Dc", anni:24, nome:"Thiaw", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"Dc", anni:28, nome:"Unai Nunez", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:23, nome:"Van Der Brempt", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:27, nome:"Vogliacco", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"W", anni:27, nome:"Zanimacchia", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:true },
  { ruolo:"Ds;E", anni:26, nome:"Zemura", quot:4.0, stip:0.8, clausola:8.0, fuoriLista:false },
  { ruolo:"A", anni:25, nome:"Aboukhlal", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"C;T", anni:24, nome:"Anjorin", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:31, nome:"Azzi", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"W;A", anni:28, nome:"Bailey", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Dc", anni:23, nome:"Balogh", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"M;C", anni:21, nome:"Belahyane", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"A", anni:25, nome:"Brenner", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Pc", anni:17, nome:"Camarda", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"M;C", anni:36, nome:"Castagnetti", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"W", anni:26, nome:"Chukwueze", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Dd;Ds;E", anni:26, nome:"Coulibaly W.", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"C;T", anni:24, nome:"Dele-Bashiru", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"C", anni:27, nome:"Douglas Luiz", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Pc", anni:39, nome:"Dzeko", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"M;C", anni:24, nome:"El Azzouzi", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Dc", anni:27, nome:"Erlic", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:22, nome:"Floriani Mussolini", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Dc", anni:32, nome:"Giannetti L.", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Por", anni:38, nome:"Guaita", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"M;C", anni:24, nome:"Hojholt", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"C", anni:24, nome:"Ilic", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"M;C", anni:24, nome:"Kaba", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"W;A", anni:27, nome:"Karlsson", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:32, nome:"Lazzari", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"B;Dd;E", anni:28, nome:"Lirola", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"A", anni:23, nome:"Luvumbo", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Dc", anni:18, nome:"Mlacic", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Pc", anni:33, nome:"Morata", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"M;C", anni:21, nome:"Ngom", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Por", anni:37, nome:"Nicolas", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"B;Dd;E", anni:22, nome:"Oyegoke", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Ds;Dc", anni:20, nome:"Rodriguez Ju.", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Dd;Ds;E", anni:32, nome:"Sabelli", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"E", anni:23, nome:"Salah-Eddine", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"W;T", anni:23, nome:"Sarmiento J.", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Por", anni:29, nome:"Scuffet", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Dc", anni:23, nome:"Siebert", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Dc", anni:19, nome:"Slotsager", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"M;C", anni:31, nome:"Tameze", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Pc", anni:33, nome:"Taremi", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"W", anni:29, nome:"Tete Morente", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:true },
  { ruolo:"Ds;E", anni:29, nome:"Tsimikas", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"M;C", anni:26, nome:"Zarraga", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"Dc", anni:20, nome:"Zatterstrom", quot:3.0, stip:0.6, clausola:6.0, fuoriLista:false },
  { ruolo:"C;T", anni:19, nome:"Adzic", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"M;C", anni:29, nome:"Al-Musrati", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"W;A", anni:26, nome:"Almqvist", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Pc", anni:22, nome:"Ambrosino", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"M;C", anni:23, nome:"Asllani", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"C;T", anni:18, nome:"Bakola", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Pc", anni:28, nome:"Bayo V.", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"M;C", anni:27, nome:"Boloca", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:22, nome:"Bonfanti", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dc", anni:27, nome:"Casale", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dd;Ds;E", anni:19, nome:"Cham", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:20, nome:"Coppola F.", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"W", anni:29, nome:"Cornet", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"C", anni:20, nome:"Cremaschi", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"B;Dd;E", anni:36, nome:"Darmian", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Pc", anni:27, nome:"De Luca", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:37, nome:"De Silvestri", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:26, nome:"Di Pardo", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dc", anni:27, nome:"Dossena", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Ds;Dc", anni:26, nome:"Ebosse", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Pc", anni:24, nome:"Elphege", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"M;C", anni:24, nome:"Engelhardt", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dc", anni:21, nome:"Faye", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"E;W", anni:19, nome:"Fini", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dd;Dc", anni:21, nome:"Goglichidze", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"M;C", anni:20, nome:"Gorter", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"W;T", anni:24, nome:"Gronbaek", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:23, nome:"Hainaut", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"C;T", anni:25, nome:"Helgason", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:20, nome:"Helland", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Ds;Dc", anni:19, nome:"Jack", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dc", anni:25, nome:"Jean", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:25, nome:"Kumbulla", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"M;C", anni:19, nome:"Liteta", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:22, nome:"Lovik", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"C", anni:27, nome:"Lovric", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:32, nome:"Lykogiannis", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:21, nome:"Marianucci", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:32, nome:"Marì", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"B;Ds;E", anni:31, nome:"Masina", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dc", anni:21, nome:"Mateus Lusuardi", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dd;Ds;E", anni:30, nome:"Mazzocchi", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:21, nome:"Missori", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Por", anni:20, nome:"Motta", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Pc", anni:25, nome:"Moumbagna", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:26, nome:"Ndaba", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:25, nome:"Nkounkou", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"M;C", anni:25, nome:"Onana J.", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Por", anni:40, nome:"Padelli", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:17, nome:"Palma", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dd;Dc", anni:32, nome:"Patric", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Pc", anni:37, nome:"Pavoletti", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"M;C", anni:28, nome:"Pickel", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"A", anni:27, nome:"Pierini", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dc", anni:28, nome:"Ravanelli", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"M;C", anni:23, nome:"Richardson", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Pc", anni:24, nome:"Rocha Livramento", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Dc", anni:28, nome:"Romagna", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:29, nome:"Rus", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"T", anni:29, nome:"Sabiri", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"W;T", anni:23, nome:"Suslov", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:22, nome:"Tchoca", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"Pc", anni:19, nome:"Trepy", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:24, nome:"Valentini N.", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"W", anni:19, nome:"Venturino", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:23, nome:"Viti", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:true },
  { ruolo:"M;C", anni:23, nome:"Vranckx", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dc", anni:20, nome:"Ziolkowski", quot:2.0, stip:0.4, clausola:4.0, fuoriLista:false },
  { ruolo:"Dd;E", anni:26, nome:"Abdulhamid", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"A", anni:20, nome:"Albarracin", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dc", anni:40, nome:"Albiol", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"T", anni:29, nome:"Alli", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Pc", anni:24, nome:"Alvarez A.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"W;T", anni:25, nome:"Arena", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Ds;E", anni:20, nome:"Arizala", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:23, nome:"Azon", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"A", anni:19, nome:"Balentien", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"M;C", anni:23, nome:"Bianco", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Ds;E", anni:33, nome:"Biraghi", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:23, nome:"Bonfanti N.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dc", anni:20, nome:"Bozhinov", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"M;C", anni:23, nome:"Braunoder", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"A", anni:18, nome:"Buffon L.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:20, nome:"Calligaris", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Ds;Dc", anni:27, nome:"Candè", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:22, nome:"Carboni F.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:23, nome:"Cavlina", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:33, nome:"Ceccherini", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:26, nome:"Christensen O.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:23, nome:"Ciocci", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"W;T", anni:19, nome:"Cissè A.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"M;C", anni:26, nome:"Collocolo", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:29, nome:"Contini", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"W;T", anni:20, nome:"Cuenca H.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:21, nome:"Dembelè A.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dc", anni:21, nome:"Denoon", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:32, nome:"Di Gennaro", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:35, nome:"Donnarumma An.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:23, nome:"Esteves T.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:19, nome:"Ferrante", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"M;C", anni:22, nome:"Fofana Sa.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:22, nome:"Frigan", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:25, nome:"Fruchtl", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:23, nome:"Furlanetto", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:31, nome:"Gabrielloni", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dc", anni:32, nome:"Gigot", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"B;Dd;Ds", anni:27, nome:"Godfrey", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dc", anni:32, nome:"Goldaniga", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:19, nome:"Gueye", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dd;Ds;E", anni:31, nome:"Hysaj", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dc", anni:22, nome:"Ilic M.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Pc", anni:21, nome:"Isaac", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:25, nome:"Israel", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"C;T", anni:27, nome:"Kastanos", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dc", anni:19, nome:"Kouadio", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"A", anni:28, nome:"Kouamè", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dd;Dc", anni:22, nome:"Kouassi", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"C;T", anni:18, nome:"Lahdo", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dd;Ds;E", anni:25, nome:"Lamptey", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:30, nome:"Lezzerini", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"W;T", anni:18, nome:"Liberali", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:24, nome:"Mandas", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"T", anni:23, nome:"Marchwinski", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dc", anni:17, nome:"Mbambi", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Pc", anni:31, nome:"Milik", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:24, nome:"Moro L.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:22, nome:"Nasti", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:21, nome:"Nava", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dc", anni:23, nome:"Ndiaye", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:18, nome:"Nunziante", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dc", anni:25, nome:"Odenthal", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dc", anni:19, nome:"Odogu", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"A", anni:28, nome:"Okereke", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dc", anni:21, nome:"Otoa", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"T;A", anni:19, nome:"Pafundi", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dc", anni:22, nome:"Palacios T.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:23, nome:"Paz Y.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dc", anni:21, nome:"Pedro Felipe", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dd;Dc", anni:20, nome:"Perez M.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:30, nome:"Perilli", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:22, nome:"Pieragnolo", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"M;C", anni:25, nome:"Pierret", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:35, nome:"Pinsoglio", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:20, nome:"Pizarro", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:25, nome:"Popa", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"W;T", anni:18, nome:"Przyborek", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:25, nome:"Quagliata", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:29, nome:"Radunovic", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"C;T", anni:26, nome:"Rafia", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dd;E", anni:19, nome:"Raterink", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:23, nome:"Rinaldi", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"M;C", anni:30, nome:"Rog", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:34, nome:"Rossi F.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Ds;E", anni:21, nome:"Rouhi", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"E", anni:26, nome:"Rui Modesto", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:24, nome:"Russo A.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"C", anni:24, nome:"Sala A.", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:22, nome:"Samooja", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"C", anni:21, nome:"Santiago", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:26, nome:"Satalino", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:23, nome:"Sava", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dc", anni:26, nome:"Schuurs", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Dd;Ds;E", anni:28, nome:"Sernicola", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:28, nome:"Sherri", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:33, nome:"Siegrist", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:34, nome:"Silvestri", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:19, nome:"Siviero", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Pc", anni:23, nome:"Skjellerup", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:28, nome:"Sommariva", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"C;T", anni:32, nome:"Stanciu", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"W;T", anni:27, nome:"Stengs", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:21, nome:"Toniolo", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:23, nome:"Tornqvist", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:20, nome:"Torriani", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Por", anni:24, nome:"Turati", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"C;T", anni:32, nome:"Valoti", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Ds;Dc", anni:22, nome:"Veroli", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:35, nome:"Vigorito", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"C", anni:19, nome:"Vural", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
  { ruolo:"Dc", anni:28, nome:"Wieteska", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:true },
  { ruolo:"Por", anni:19, nome:"Zelezny", quot:1.0, stip:0.2, clausola:2.0, fuoriLista:false },
];
